# Generated by Django 4.2.8 on 2024-01-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_vis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashes',
            name='latitude',
            field=models.FloatField(verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='crashes',
            name='longitude',
            field=models.FloatField(verbose_name='longitude'),
        ),
    ]
