# Generated by Django 4.2.8 on 2024-01-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_vis', '0002_alter_crashes_latitude_alter_crashes_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('latitude', models.FloatField(verbose_name='longitude')),
            ],
        ),
        migrations.DeleteModel(
            name='crashes',
        ),
    ]
